frontend:
  host: amqp://statisticuser:statisticpasswd@192.168.1.129:5672/statistic
  type: 2
  items:
    reqlog:
      exchangename: statistic_reqlog
      exchangetype: direct
      keys:
        - cgi_web
        - business_base
        - business_user
        - service_base
        - service_user